server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: 12345678
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: validate


    #show-sql: true → jpa가 자동으로 만들어주는 query문을 console에서 볼 것인지 여부
  #database-platform → 사용할 DB의 Dialect설정
#database : mysql → 사용할 DB종류
 # hibernate.ddl-auto —> update  가장 중요한 옵션 create쓰지 말 것


